@mptr and also split tests into subpackages
commit 291dd01ba0579bbcf835ec6e5552e940a099b599
Author: Jean-Louis Leroy <jl@leroy.nyc>
Date:   Mon Jul 24 18:38:56 2017 -0400

    make gdc survive tests

commit b32a9ae25072642d137a9df2ec20ab9b041fb394
Author: Jean-Louis Leroy <jl@leroy.nyc>
Date:   Mon Jul 24 17:51:50 2017 -0400

    improve travis.sh

commit 6baa65ba8c600266123657302dcb7c7b4ee0dd3b
Author: Jean-Louis Leroy <jl@leroy.nyc>
Date:   Mon Jul 24 17:47:23 2017 -0400

    reorganize test dubs

commit 950667ca45cfb8b38a99bb41074fbc6185d7d661
Author: Jean-Louis Leroy <jl@leroy.nyc>
Date:   Mon Jul 24 16:21:24 2017 -0400

    restrict

commit db00a866e50dc93b1b3a63874a5a9448d7204e9f
Author: Jean-Louis Leroy <jl@yorel.be>
Date:   Sun Jul 23 05:26:05 2017 -0400

    improve benchmarks

commit 22215177a045782373dee341c8537d85166e467f
Author: Jean-Louis Leroy <jl@leroy.nyc>
Date:   Sun Jul 23 04:42:39 2017 -0400

    add mptrhash.d

commit e0c83afdbd7a2b94a78b76f7723b6d6fce8474aa
Author: Jean-Louis Leroy <jl@leroy.nyc>
Date:   Sun Jul 23 04:28:22 2017 -0400

    rename methodIndex to mptr

commit ac73c07101876a5f704531af901169b9305b91ff
Author: Jean-Louis Leroy <jl@leroy.nyc>
Date:   Sun Jul 23 03:48:25 2017 -0400

    begins to work

commit 58997fcd663eb8ae0da43bcbf909b3e7e2a48b11
Author: Jean-Louis Leroy <jl@leroy.nyc>
Date:   Fri Jul 21 17:02:43 2017 -0400

    implement alternative index placement

diff --git a/dev/run-everything b/dev/run-everything
--- a/dev/run-everything
+++ b/dev/run-everything
@@ -2,6 +2,8 @@
 
 errors=0
 
+DC_EXCLUSIONS='mptr|method\('
+
 echo test openmethods...
 
 if ! dub test -q openmethods $*;
@@ -10,9 +12,9 @@ then
     errors=1
 fi
 
-for target in $(ls examples | grep -v synopsis)
+for target in $(ls examples)
 do
-    if [[ "$DC" == 'gdc' ]] && grep --quiet 'method(' `find examples/$target -name '*.d'`;
+    if [[ "$DC" == 'gdc' ]] && grep --quiet -P $DC_EXCLUSIONS `find examples/$target -name '*.d'`;
     then
         echo SKIP $target
         continue
@@ -25,19 +27,27 @@ do
         echo "ERROR"
         errors=1
     fi
+
+    echo run $target...
+
+    if ! dub run -q openmethods:$target $*;
+    then
+        echo "ERROR"
+        errors=1
+    fi
 done
 
-for target in $(ls examples)
+for target in $(ls tests)
 do
-    if [[ "$DC" == 'gdc' ]] && grep --quiet 'method(' `find examples/$target -name '*.d'`;
+    if [[ "$DC" == 'gdc' ]] && grep --quiet -P $DC_EXCLUSIONS `find tests/$target -name '*.d'`;
     then
         echo SKIP $target
         continue
     fi
 
-    echo run $target...
+    echo test $target...
 
-    if ! dub run -q openmethods:$target $*;
+    if ! dub test -q openmethods:$target $*;
     then
         echo "ERROR"
         errors=1
